---
- name: Set Kubelet listen
  lineinfile:
    path: /etc/kubernetes/kubelet
    regexp: '^KUBELET_ADDRESS'
    line: 'KUBELET_ADDRESS="--address=0.0.0.0"'
    
- name: Set Kubelet hostname option
  lineinfile:
    path: /etc/kubernetes/kubelet
    regexp: '^KUBELET_HOSTNAME'
    line: 'KUBELET_HOSTNAME=""'
    
- name: Set Kubelet configuration reference
  lineinfile:
    path: /etc/kubernetes/kubelet
    regexp: '^KUBELET_ARGS'
    line: 'KUBELET_ARGS="--cgroup-driver=systemd --kubeconfig=/etc/kubernetes/master-kubeconfig.yaml"'
    
- name: Set Kubelet configuration file
  template:
    src: 'master-kubeconfig.yaml.j2'
    dest: '/etc/kubernetes/master-kubeconfig.yaml'

- name: Enable and start services
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items:
    - flanneld
    - docker
    - kube-proxy
    - kubelet
